// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SanblasBackend.Data;

#nullable disable

namespace SanblasBackend.Migrations
{
    [DbContext(typeof(GlobalContex))]
    [Migration("20260617032455_AddObservacionEstadoInscripcionCatequesis")]
    partial class AddObservacionEstadoInscripcionCatequesis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SanblasBackend.Models.AdecuacionCatequizando", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionAdecuacion")
                        .HasColumnType("text");

                    b.Property<int>("InscripcionCatequesisId")
                        .HasColumnType("integer");

                    b.Property<bool?>("RequiereAdecuacionCentroEducativo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionCatequesisId")
                        .IsUnique();

                    b.ToTable("AdecuacionesCatequizando");
                });

            modelBuilder.Entity("SanblasBackend.Models.BautismoCatequizando", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Asiento")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Folio")
                        .HasColumnType("text");

                    b.Property<int>("InscripcionCatequesisId")
                        .HasColumnType("integer");

                    b.Property<string>("Parroquia")
                        .HasColumnType("text");

                    b.Property<string>("Tomo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionCatequesisId")
                        .IsUnique();

                    b.ToTable("BautismosCatequizando");
                });

            modelBuilder.Entity("SanblasBackend.Models.Catequizando", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DireccionExacta")
                        .HasColumnType("text");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<int>("InscripcionCatequesisId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionCatequesisId")
                        .IsUnique();

                    b.ToTable("Catequizandos");
                });

            modelBuilder.Entity("SanblasBackend.Models.CondicionSaludCatequizando", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEnfermedad")
                        .HasColumnType("text");

                    b.Property<int>("InscripcionCatequesisId")
                        .HasColumnType("integer");

                    b.Property<bool?>("PortadorEnfermedadCronica")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionCatequesisId")
                        .IsUnique();

                    b.ToTable("CondicionesSaludCatequizando");
                });

            modelBuilder.Entity("SanblasBackend.Models.FormSacra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SegundoApellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoSacramento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("FormSacras");
                });

            modelBuilder.Entity("SanblasBackend.Models.InscripcionCatequesis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CentroCatequesis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaActualizacionEstado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NivelAInscribirse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservacionAdministrativa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InscripcionesCatequesis");
                });

            modelBuilder.Entity("SanblasBackend.Models.MadreCatequizando", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("DireccionExacta")
                        .HasColumnType("text");

                    b.Property<int>("InscripcionCatequesisId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provincia")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InscripcionCatequesisId")
                        .IsUnique();

                    b.ToTable("MadresCatequizando");
                });

            modelBuilder.Entity("SanblasBackend.Models.AdecuacionCatequizando", b =>
                {
                    b.HasOne("SanblasBackend.Models.InscripcionCatequesis", "InscripcionCatequesis")
                        .WithOne("Adecuacion")
                        .HasForeignKey("SanblasBackend.Models.AdecuacionCatequizando", "InscripcionCatequesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InscripcionCatequesis");
                });

            modelBuilder.Entity("SanblasBackend.Models.BautismoCatequizando", b =>
                {
                    b.HasOne("SanblasBackend.Models.InscripcionCatequesis", "InscripcionCatequesis")
                        .WithOne("Bautismo")
                        .HasForeignKey("SanblasBackend.Models.BautismoCatequizando", "InscripcionCatequesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InscripcionCatequesis");
                });

            modelBuilder.Entity("SanblasBackend.Models.Catequizando", b =>
                {
                    b.HasOne("SanblasBackend.Models.InscripcionCatequesis", "InscripcionCatequesis")
                        .WithOne("Catequizando")
                        .HasForeignKey("SanblasBackend.Models.Catequizando", "InscripcionCatequesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InscripcionCatequesis");
                });

            modelBuilder.Entity("SanblasBackend.Models.CondicionSaludCatequizando", b =>
                {
                    b.HasOne("SanblasBackend.Models.InscripcionCatequesis", "InscripcionCatequesis")
                        .WithOne("CondicionSalud")
                        .HasForeignKey("SanblasBackend.Models.CondicionSaludCatequizando", "InscripcionCatequesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InscripcionCatequesis");
                });

            modelBuilder.Entity("SanblasBackend.Models.MadreCatequizando", b =>
                {
                    b.HasOne("SanblasBackend.Models.InscripcionCatequesis", "InscripcionCatequesis")
                        .WithOne("Madre")
                        .HasForeignKey("SanblasBackend.Models.MadreCatequizando", "InscripcionCatequesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InscripcionCatequesis");
                });

            modelBuilder.Entity("SanblasBackend.Models.InscripcionCatequesis", b =>
                {
                    b.Navigation("Adecuacion")
                        .IsRequired();

                    b.Navigation("Bautismo")
                        .IsRequired();

                    b.Navigation("Catequizando")
                        .IsRequired();

                    b.Navigation("CondicionSalud")
                        .IsRequired();

                    b.Navigation("Madre")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
