CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "FormSacras" (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "PrimerApellido" text NOT NULL,
    "SegundoApellido" text NOT NULL,
    "Cedula" text NOT NULL,
    "Correo" text NOT NULL,
    "Telefono" text NOT NULL,
    "TipoSacramento" integer NOT NULL,
    "Motivo" text NOT NULL,
    "Estado" text,
    CONSTRAINT "PK_FormSacras" PRIMARY KEY (id)
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260615182400_InitialCreate', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "FormSacras" ALTER COLUMN "TipoSacramento" TYPE text;

CREATE TABLE "InscripcionesCatequesis" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CentroCatequesis" text NOT NULL,
    "NivelAInscribirse" text NOT NULL,
    "Estado" text NOT NULL DEFAULT 'Pendiente',
    "FechaSolicitud" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_InscripcionesCatequesis" PRIMARY KEY ("Id")
);

CREATE TABLE "AdecuacionesCatequizando" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InscripcionCatequesisId" integer NOT NULL,
    "RequiereAdecuacionCentroEducativo" boolean,
    "DescripcionAdecuacion" text,
    CONSTRAINT "PK_AdecuacionesCatequizando" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AdecuacionesCatequizando_InscripcionesCatequesis_Inscripcio~" FOREIGN KEY ("InscripcionCatequesisId") REFERENCES "InscripcionesCatequesis" ("Id") ON DELETE CASCADE
);

CREATE TABLE "BautismosCatequizando" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InscripcionCatequesisId" integer NOT NULL,
    "Parroquia" text,
    "Fecha" date,
    "Tomo" text,
    "Folio" text,
    "Asiento" text,
    CONSTRAINT "PK_BautismosCatequizando" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_BautismosCatequizando_InscripcionesCatequesis_InscripcionCa~" FOREIGN KEY ("InscripcionCatequesisId") REFERENCES "InscripcionesCatequesis" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Catequizandos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InscripcionCatequesisId" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Apellidos" text NOT NULL,
    "FechaNacimiento" date NOT NULL,
    "DireccionExacta" text,
    CONSTRAINT "PK_Catequizandos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Catequizandos_InscripcionesCatequesis_InscripcionCatequesis~" FOREIGN KEY ("InscripcionCatequesisId") REFERENCES "InscripcionesCatequesis" ("Id") ON DELETE CASCADE
);

CREATE TABLE "CondicionesSaludCatequizando" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InscripcionCatequesisId" integer NOT NULL,
    "PortadorEnfermedadCronica" boolean,
    "DescripcionEnfermedad" text,
    CONSTRAINT "PK_CondicionesSaludCatequizando" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CondicionesSaludCatequizando_InscripcionesCatequesis_Inscri~" FOREIGN KEY ("InscripcionCatequesisId") REFERENCES "InscripcionesCatequesis" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MadresCatequizando" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "InscripcionCatequesisId" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Apellidos" text NOT NULL,
    "DireccionExacta" text,
    "Ciudad" text,
    "Provincia" text,
    "Telefono" text NOT NULL,
    CONSTRAINT "PK_MadresCatequizando" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MadresCatequizando_InscripcionesCatequesis_InscripcionCateq~" FOREIGN KEY ("InscripcionCatequesisId") REFERENCES "InscripcionesCatequesis" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_AdecuacionesCatequizando_InscripcionCatequesisId" ON "AdecuacionesCatequizando" ("InscripcionCatequesisId");

CREATE UNIQUE INDEX "IX_BautismosCatequizando_InscripcionCatequesisId" ON "BautismosCatequizando" ("InscripcionCatequesisId");

CREATE UNIQUE INDEX "IX_Catequizandos_InscripcionCatequesisId" ON "Catequizandos" ("InscripcionCatequesisId");

CREATE UNIQUE INDEX "IX_CondicionesSaludCatequizando_InscripcionCatequesisId" ON "CondicionesSaludCatequizando" ("InscripcionCatequesisId");

CREATE UNIQUE INDEX "IX_MadresCatequizando_InscripcionCatequesisId" ON "MadresCatequizando" ("InscripcionCatequesisId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260616044425_AddInscripcionesCatequesis', '10.0.9');

COMMIT;

START TRANSACTION;
ALTER TABLE "InscripcionesCatequesis" ADD "FechaActualizacionEstado" timestamp with time zone;

ALTER TABLE "InscripcionesCatequesis" ADD "ObservacionAdministrativa" text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260617032455_AddObservacionEstadoInscripcionCatequesis', '10.0.9');

COMMIT;

