START TRANSACTION;
CREATE TABLE "Eventos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Titulo" text NOT NULL,
    "Descripcion" text NOT NULL,
    "FechaInicio" timestamp with time zone NOT NULL,
    "FechaFin" timestamp with time zone,
    "Lugar" text NOT NULL,
    "Publicado" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Eventos" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260618050328_AddEventos', '10.0.9');

COMMIT;

